import { task } from "./content.mjs";
export const projects = [
  {
    ...task(
      "responsive-business-website",
      "Responsive Business Website",
      "A small repair business needs Home, About, Services and Contact information. Create your own design rather than reproducing a finished screenshot.",
      [
        "Semantic HTML and logical headings",
        "Responsive layout and mobile navigation at 320, 390, 768, 1024 and 1440 CSS pixels",
        "Accessible labelled contact form with honest local-only submission status",
        "Useful image alternatives, readable type and contrast",
        "Keyboard operation, visible focus and no unintended horizontal overflow",
        "README: purpose, technologies, implementation and accessibility notes",
      ],
      "Explain two semantic choices and one responsive breakpoint.",
      "Add an extra service and long contact instructions while preserving usability.",
    ),
    level: "Foundation",
    prerequisites: [
      "web-how-it-works",
      "html-core",
      "css-core",
      "responsive-web",
      "accessibility-foundations",
      "browser-devtools",
    ],
    skills: [
      "HTML",
      "CSS",
      "Responsive Design",
      "Accessibility",
      "Frontend Development",
    ],
    portfolioEligible: true,
  },
  {
    ...task(
      "vanilla-js-task-manager",
      "Vanilla JavaScript Task Manager",
      "An individual needs a browser task manager to replace paper notes. Use HTML, CSS and Vanilla JavaScript; do not use React.",
      [
        "Create, display, edit and delete tasks",
        "Mark complete and incomplete using stable identity",
        "All, Active and Completed filters derive from one underlying collection",
        "Reject empty titles and show a useful empty state",
        "Persist and restore tasks after refresh",
        "Handle missing, malformed and wrong-shaped stored data without a crash or silent destructive overwrite",
        "Labelled input, semantic buttons, visible focus and non-colour-only status",
        "Usable on phone, tablet and desktop with no unintended overflow",
        "Behaviour checks: render, valid add, empty reject, complete, edit, delete, both filters, reload and missing storage",
        "Debug a variation in which completed tasks revert after refresh",
        "README: purpose, features, technologies, learning, persistence and known limits",
      ],
      "Explain serialization, restoration and the controlled bug’s root cause.",
      "Add task priority and update filters while accepting older saved records.",
    ),
    level: "Foundation",
    prerequisites: [
      "javascript-programming-basics",
      "javascript-conditions",
      "javascript-functions",
      "javascript-data-collections",
      "javascript-debugging-foundations",
      "javascript-dom",
      "javascript-events",
      "javascript-forms-validation",
      "javascript-array-transformations",
      "javascript-browser-storage",
      "accessibility-foundations",
      "responsive-web",
    ],
    skills: [
      "JavaScript",
      "DOM",
      "Events",
      "Forms",
      "Array Transformations",
      "Browser Storage",
      "Accessibility",
      "Responsive Design",
      "Debugging",
    ],
    portfolioEligible: true,
  },
  {
    ...task(
      "expense-management-application",
      "Expense Management Application",
      "Help an individual track expenses with a usable responsive browser application.",
      [
        "Create, edit and delete expenses with stable identity",
        "Validate amounts and categories",
        "Filter and derive totals without duplicate state",
        "Persist records and handle corrupt data",
        "Use a documented read API for category guidance or clearly labelled local fixtures",
        "Loading, empty and error states",
        "Accessible controls, responsive layout and behavioural tests",
        "README documents data location and limits",
      ],
      "Explain stored versus derived data and API failure handling.",
      "Add a recurring-expense view without counting future expenses as already paid.",
    ),
    level: "Intermediate",
    prerequisites: [
      "vanilla-js-task-manager",
      "javascript-modules",
      "http-rest-apis",
      "testing-foundations",
    ],
    skills: [
      "JavaScript",
      "API Integration",
      "Persistence",
      "Testing",
      "Accessibility",
    ],
    portfolioEligible: true,
  },
  {
    ...task(
      "react-developer-preferences",
      "Developer Preferences Application",
      "Extend the historical Shared Preferences exercise into a small routed React application.",
      [
        "Multiple components use shared language/theme settings",
        "Controlled form, effect cleanup and a custom context hook",
        "Validated local persistence and useful error feedback",
        "Routing with direct-load and not-found behaviour",
        "Accessible responsive controls",
        "Tests for change, restore, invalid storage and shared consumers",
        "README acknowledges the original Programming Language Toggle App",
      ],
      "Explain state, props, effects and Context responsibilities.",
      "Add a per-project preference override without duplicating global state.",
    ),
    level: "Foundation",
    prerequisites: [
      "shared-preferences",
      "react-routing",
      "testing-foundations",
    ],
    skills: [
      "React",
      "Context",
      "Forms",
      "Routing",
      "Browser Storage",
      "Accessibility",
      "Testing",
    ],
    portfolioEligible: true,
  },
  {
    ...task(
      "task-management-dashboard",
      "Task Management Dashboard",
      "A small team needs a frontend for a documented task API. Local fixtures must be identified as fixtures; do not claim real team collaboration when no service exists.",
      [
        "Routed task list, detail and settings",
        "Create/update/delete contracts, validation and clear pending states",
        "Filtering and derived summaries",
        "Loading, empty, denied-access and service-failure states",
        "Responsive accessible forms and navigation",
        "No frontend-only authorization claim",
        "Unit/component and integration checks",
        "README includes API contract, setup and limitations",
      ],
      "Explain state ownership and how failed updates recover.",
      "Add a read-only role and describe the matching server authorization contract.",
    ),
    level: "Intermediate",
    prerequisites: [
      "react-application-development",
      "react-developer-preferences",
      "git-foundations",
    ],
    skills: [
      "React",
      "API Integration",
      "Testing",
      "Git",
      "Accessibility",
      "State Ownership",
    ],
    portfolioEligible: true,
  },
  {
    ...task(
      "production-javascript-dashboard",
      "Production-Style JavaScript Dashboard",
      "Build a modular dashboard with controlled asynchronous data and measured behaviour without a framework requirement.",
      [
        "Bounded/cancellable data loading",
        "Testable modules and immutable transformations",
        "Accessible loading/error/empty states",
        "Performance baseline and focused improvement",
        "Cleanup across repeated navigation",
        "Regression tests and architecture notes",
      ],
      "Explain closure, event-loop and concurrency decisions in the implementation.",
      "Support an additional data source with different failure semantics.",
    ),
    level: "Advanced",
    prerequisites: [
      "expense-management-application",
      "javascript-advanced",
      "frontend-performance",
      "testing-strategy",
    ],
    skills: [
      "JavaScript",
      "Architecture",
      "Performance",
      "Testing",
      "API Integration",
    ],
    portfolioEligible: true,
  },
  {
    ...task(
      "production-saas-dashboard",
      "Production SaaS Dashboard",
      "Build a production-style frontend with analytics, complex forms and reusable components. The title describes the brief, not a production-readiness claim.",
      [
        "Deliberate state and component architecture",
        "Validated API handling with recovery and cancellation",
        "Complex accessible forms and modal interactions",
        "Code splitting with loading and failure recovery",
        "Measured performance improvements",
        "Behaviour and integration test strategy",
        "Security boundary review",
        "Repository documentation and reproducible preview deployment",
      ],
      "Explain architecture, testing scope and one rejected optimization.",
      "Add a workspace-switching requirement while preserving isolation and draft recovery.",
    ),
    level: "Advanced",
    prerequisites: [
      "task-management-dashboard",
      "react-advanced-architecture",
      "accessible-components",
      "frontend-performance",
      "testing-strategy",
      "frontend-security",
    ],
    skills: [
      "React",
      "Architecture",
      "Accessibility",
      "Performance",
      "Testing",
      "Security",
    ],
    portfolioEligible: true,
  },
  {
    ...task(
      "frontend-capstone",
      "Professional Frontend Capstone",
      "A community training organization needs a responsive workshop management frontend for an agreed API. Clarify roles, cancellation rules and draft handling before choosing the architecture.",
      [
        "Semantic HTML and responsive CSS",
        "JavaScript/React with deliberate state and form design",
        "API integration with loading, empty, error, conflict and retry states",
        "Accessibility evidence including keyboard, focus, labels, errors and manual assistive-technology checks",
        "Functional, component and integration tests for important behaviours",
        "Git history, review notes, architecture decisions and README",
        "Measured performance on declared scenarios",
        "Security boundaries, no client secrets and server authorization contract",
        "Reproducible preview deployment and recovery notes",
        "Debug an unfamiliar defect, explain selected code and implement the post-pass change",
        "Portfolio package: problem, solution, technologies, demonstrated skills, test/accessibility/responsive evidence and optional source/live links",
      ],
      "Explain state ownership, API recovery, accessibility and what would change at a larger scale.",
      "After the initial requirements are met, the client needs saved filters, keyboard-operable bulk selection and recovery from a rejected bulk update. Extend the same implementation and preserve earlier behaviours.",
    ),
    level: "Professional",
    prerequisites: [
      "professional-frontend",
      "production-saas-dashboard",
      "deployment-fundamentals",
    ],
    skills: [
      "Frontend Development",
      "React",
      "JavaScript",
      "Accessibility",
      "Testing",
      "Git",
      "Performance",
      "Security",
      "Deployment",
      "Technical Communication",
    ],
    portfolioEligible: true,
  },
];
export const checkpoints = [
  {
    ...task(
      "web-foundations-checkpoint-v1",
      "Web Foundations Practical Checkpoint",
      "Create a Community Workshop Website, distinct from the business training project.",
      [
        "Semantic content and workshop schedule",
        "Labelled registration form",
        "Responsive layout at required viewport classes",
        "Keyboard access, focus and readable contrast",
        "Diagnose a controlled missing-asset or layout defect",
        "Provide explanation and test observations",
      ],
      "Explain how structure and layout serve the content.",
      "Add another workshop with a longer title and preserve navigation.",
    ),
    level: "Foundation",
    prerequisites: ["responsive-business-website"],
    skills: ["HTML", "CSS", "Responsive Design", "Accessibility", "Debugging"],
  },
  {
    ...task(
      "javascript-foundation-checkpoint-v1",
      "JavaScript Foundation Practical Checkpoint",
      "Build a Personal Reading List Manager from a brief without a supplied architecture.",
      [
        "Add, edit and remove reading items",
        "Mark status and filter from underlying data",
        "Validate input",
        "Persist and restore structured data",
        "Handle missing and malformed storage",
        "Accessible controls and responsive layout",
        "Fix a controlled persistence defect",
        "Explain selected functions, data shape and events",
      ],
      "Explain how the UI reflects application data and how restoration works.",
      "Add a reading-priority field while keeping older records usable.",
    ),
    level: "Foundation",
    prerequisites: ["vanilla-js-task-manager"],
    skills: [
      "JavaScript",
      "DOM",
      "Events",
      "Validation",
      "Persistence",
      "Accessibility",
      "Debugging",
    ],
  },
  {
    ...task(
      "frontend-foundation-checkpoint-v1",
      "Frontend Developer Foundation Checkpoint",
      "Build a small accessible community directory with React and a documented read API.",
      [
        "Semantic responsive interface",
        "JavaScript and React data/state reasoning",
        "Git workflow and README",
        "Loading, error and empty states",
        "Forms and accessibility behaviour",
        "Important behavioural tests",
        "Explain and modify existing code",
      ],
      "Explain the full browser-to-API data flow.",
      "Add a saved filter with a safe first-run default.",
    ),
    level: "Foundation",
    prerequisites: [
      "web-foundations-checkpoint-v1",
      "javascript-foundation-checkpoint-v1",
      "react-foundation-checkpoint-v1",
      "react-developer-preferences",
      "git-foundations",
      "testing-foundations",
    ],
    skills: [
      "Frontend Development",
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Git",
      "Accessibility",
      "API Integration",
      "Testing",
    ],
  },
];
const path = (id, title, level, stages, certificateTitle) => ({
  id,
  title,
  version: "1.0.0",
  level,
  stages: stages.map(([title, requirements]) => ({ title, requirements })),
  certificateTitle,
  completion: {
    mode: "all-required-evidence",
    optionalExplorationBlocks: false,
  },
  issuanceEnabled: false,
});
export const paths = [
  path(
    "web-foundations-v1",
    "Web Development Foundations",
    "Foundation",
    [
      ["Understanding the Web", ["web-how-it-works"]],
      ["HTML Foundations", ["html-core"]],
      ["CSS Foundations", ["css-core"]],
      ["Responsive Design", ["responsive-web"]],
      ["Accessibility Foundations", ["accessibility-foundations"]],
      ["Developer Tools", ["browser-devtools"]],
      ["Foundation Project", ["responsive-business-website"]],
      ["Practical Checkpoint", ["web-foundations-checkpoint-v1"]],
    ],
    "Web Development Foundations — Verified Practical Skills Certificate",
  ),
  path(
    "javascript-foundations-v1",
    "JavaScript Foundations",
    "Foundation",
    [
      ["Programming Fundamentals", ["javascript-programming-basics"]],
      ["Decisions and Logic", ["javascript-conditions"]],
      ["Functions", ["javascript-functions"]],
      ["Collections and Data", ["javascript-data-collections"]],
      ["Debugging", ["javascript-debugging-foundations"]],
      ["DOM", ["javascript-dom"]],
      ["Events", ["javascript-events"]],
      ["Forms", ["javascript-forms-validation"]],
      ["Data Transformation", ["javascript-array-transformations"]],
      ["Browser Persistence", ["javascript-browser-storage"]],
      ["Foundation Project", ["vanilla-js-task-manager"]],
      ["Practical Checkpoint", ["javascript-foundation-checkpoint-v1"]],
    ],
    "JavaScript Foundations — Verified Practical Skills Certificate",
  ),
  path(
    "javascript-application-development-v1",
    "JavaScript Application Development",
    "Intermediate",
    [
      ["Module Boundaries", ["javascript-modules"]],
      ["Asynchronous JavaScript", ["javascript-async"]],
      ["HTTP and APIs", ["http-rest-apis"]],
      ["Behavioural Testing", ["testing-foundations"]],
      ["Intermediate Project", ["expense-management-application"]],
      ["React Entry or Deeper JavaScript", ["react-entry"]],
    ],
    "JavaScript Application Development — Verified Practical Skills Certificate",
  ),
  path(
    "react-foundations-v1",
    "React Foundations",
    "Foundation",
    [
      ["Practical JavaScript Entry", ["react-entry"]],
      ["React Beginner", ["react-beginner"]],
      ["State Ownership", ["react-state-composition"]],
      ["Forms, Effects and Hooks", ["react-forms-effects"]],
      ["Shared Preferences", ["react-context"]],
      ["Routing", ["react-routing"]],
      ["Foundation Project", ["react-developer-preferences"]],
      ["Practical Checkpoint", ["react-foundation-checkpoint-v1"]],
    ],
    "React Foundations — Verified Practical Skills Certificate",
  ),
  path(
    "frontend-developer-foundation-v1",
    "Frontend Developer Foundation",
    "Foundation",
    [
      ["Web Evidence", ["web-foundations-checkpoint-v1"]],
      ["JavaScript Evidence", ["javascript-foundation-checkpoint-v1"]],
      ["Git and APIs", ["git-foundations", "http-rest-apis"]],
      [
        "React and Testing",
        ["react-developer-preferences", "testing-foundations"],
      ],
      ["Combined Practical Checkpoint", ["frontend-foundation-checkpoint-v1"]],
    ],
    "Frontend Developer Foundation — Verified Practical Skills Certificate",
  ),
  path(
    "frontend-developer-v1",
    "Frontend Developer",
    "Professional",
    [
      [
        "A · Web Foundations",
        ["web-how-it-works", "html-core", "css-core", "browser-devtools"],
      ],
      [
        "B · Interactive Web",
        [
          "javascript-programming-basics",
          "javascript-conditions",
          "javascript-functions",
          "javascript-data-collections",
          "javascript-debugging-foundations",
          "javascript-dom",
          "javascript-events",
          "javascript-forms-validation",
        ],
      ],
      [
        "C · Application Foundations",
        [
          "responsive-web",
          "accessibility-foundations",
          "git-foundations",
          "javascript-array-transformations",
          "javascript-browser-storage",
          "vanilla-js-task-manager",
          "javascript-foundation-checkpoint-v1",
        ],
      ],
      [
        "D · Data and APIs",
        [
          "javascript-modules",
          "javascript-async",
          "http-rest-apis",
          "expense-management-application",
        ],
      ],
      [
        "E · React",
        [
          "react-entry",
          "react-beginner",
          "react-state-composition",
          "react-forms-effects",
          "react-context",
          "react-routing",
          "react-developer-preferences",
        ],
      ],
      [
        "F · Application Development",
        [
          "testing-foundations",
          "react-application-development",
          "task-management-dashboard",
        ],
      ],
      [
        "G · Advanced Frontend",
        [
          "javascript-advanced",
          "react-advanced-architecture",
          "accessible-components",
          "frontend-performance",
          "testing-strategy",
          "frontend-security",
          "production-javascript-dashboard",
          "production-saas-dashboard",
        ],
      ],
      [
        "H · Professional Frontend",
        ["deployment-fundamentals", "professional-frontend"],
      ],
      ["I · Capstone", ["frontend-capstone"]],
      ["J · Optional Specialization", []],
    ],
    "Professional Frontend Developer — Verified Practical Skills Certificate",
  ),
];
export const optionalSpecializations = [
  {
    id: "react-specialist",
    status: "assessment-specification",
    required: ["react-specialist-assessment-v1"],
    enabled: false,
  },
  {
    id: "accessibility-specialist",
    status: "future-scope",
    required: [],
    enabled: false,
  },
  {
    id: "frontend-performance-specialist",
    status: "future-scope",
    required: [],
    enabled: false,
  },
  {
    id: "ui-architecture-specialist",
    status: "future-scope",
    required: [],
    enabled: false,
  },
];
paths.push(
  path(
    "react-application-development-v1",
    "React Application Development",
    "Intermediate",
    [
      [
        "Foundation Evidence",
        ["react-foundation-checkpoint-v1", "react-developer-preferences"],
      ],
      ["Application Development", ["react-application-development"]],
      ["Project", ["task-management-dashboard"]],
      ["Practical Checkpoint", ["frontend-intermediate-checkpoint-v1"]],
    ],
    "React Application Development — Verified Practical Skills Certificate",
  ),
);
paths.push(
  path(
    "advanced-frontend-v1",
    "Advanced Frontend Development",
    "Advanced",
    [
      [
        "Intermediate Evidence",
        ["task-management-dashboard", "frontend-intermediate-checkpoint-v1"],
      ],
      [
        "Advanced Reasoning",
        ["javascript-advanced", "react-advanced-architecture"],
      ],
      [
        "Quality Across Boundaries",
        [
          "accessible-components",
          "frontend-performance",
          "testing-strategy",
          "frontend-security",
        ],
      ],
      ["Advanced Project", ["production-saas-dashboard"]],
      ["Practical Checkpoint", ["react-advanced-checkpoint-v1"]],
    ],
    "Advanced Frontend Development — Verified Practical Skills Certificate",
  ),
);
