import { mkdir, writeFile, readFile, copyFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const sharp = require(process.env.SHARP_PATH || 'sharp');
const root = 'public/brand';
await mkdir(root, { recursive:true });
await mkdir('src/assets/brand', { recursive:true });
const paths = '<path d="m18 16 4-4-4-4m-12 0-4 4 4 4m8.5-12-5 16"/>';
const ink = 'hsl(222,20%,7%)', blue = 'hsl(199,89%,48%)';
const glyph = `<g transform="translate(4 4)" fill="none" stroke="${ink}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${paths}</g>`;
const master = await readFile('src/assets/brand/mark.svg', 'utf8');
await writeFile(`${root}/mark.svg`,master);
await writeFile('public/icon.svg',master);
const mask = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" fill="${blue}"/><g transform="translate(6.4 6.4) scale(.6)">${glyph}</g></svg>`;
await writeFile(`${root}/maskable.svg`,mask);
await writeFile(`${root}/monochrome.svg`,`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${paths}</g></svg>`);
await writeFile(`${root}/notification.svg`,`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="none" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${paths}</g></svg>`);
for (const size of [32,180,192,512,1024]) await sharp(Buffer.from(master)).resize(size,size).png().toFile(`${root}/icon-${size}.png`);
await sharp(Buffer.from(mask)).resize(512,512).png().toFile(`${root}/maskable-512.png`);
const social = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630"><rect width="1200" height="630" fill="${ink}"/><g transform="translate(80 70) scale(3)">${master.replace(/<svg[^>]+>|<\/svg>/g,'')}</g><g fill="#edf0f3" font-family="Arial,sans-serif"><text x="205" y="134" font-size="48" font-weight="bold">CodeForge</text><text x="80" y="305" font-size="72" font-weight="bold">Learn to build.</text><text x="80" y="398" font-size="72" font-weight="bold" fill="${blue}">Not prompt.</text><text x="80" y="525" font-size="28">JavaScript and React learning • Development preview</text></g></svg>`;
await writeFile('src/assets/brand/social.svg',social);
await sharp(Buffer.from(social)).png().toFile(`${root}/social.png`);
await copyFile('node_modules/lucide-react/LICENSE','src/assets/brand/LUCIDE-LICENSE.txt');
await copyFile('node_modules/lucide-react/LICENSE',`${root}/LUCIDE-LICENSE.txt`);
const files = ['mark.svg','maskable.svg','monochrome.svg','notification.svg',...[32,180,192,512,1024].map(n=>`icon-${n}.png`),'maskable-512.png','social.png'];
await writeFile('src/assets/brand/manifest.json',JSON.stringify({ version:'1.0',status:'derived-assets-pending-release-signoff',assets:files.map(file=>({id:file.replace(/\./g,'-'),name:`CodeForge ${file}`,purpose:file.includes('social')?'Default public sharing':file.includes('notification')?'Native notification candidate':'Product identity',sourceFile:file.includes('social')?'src/assets/brand/social.svg':'src/assets/brand/mark.svg',outputFile:`${root}/${file}`,format:file.split('.').pop(),variant:file,platform:file.includes('1024')||file.includes('notification')?'native candidate; package integration pending':'web',provenance:'Derived from existing CodeForge blue tile and Lucide Code2 paths',licenceStatus:'Lucide ISC notice retained; ownership review pending',productionApproved:false}))},null,2)+'\n');
await writeFile('public/manifest.webmanifest',JSON.stringify({id:'/',name:'CodeForge',short_name:'CodeForge',description:'Learn JavaScript and React through practical coding exercises.',start_url:'/',scope:'/',display:'standalone',background_color:'#0e1015',theme_color:'#0da2e7',icons:[{src:'/brand/icon-192.png',sizes:'192x192',type:'image/png',purpose:'any'},{src:'/brand/icon-512.png',sizes:'512x512',type:'image/png',purpose:'any'},{src:'/brand/maskable-512.png',sizes:'512x512',type:'image/png',purpose:'maskable'}]},null,2)+'\n');
const native = 'src/assets/brand/platforms';
for (const platform of ['android','ios','huawei','windows','splash']) await mkdir(`${native}/${platform}`, {recursive:true});
for (const size of [48,72,96,144,192]) await sharp(Buffer.from(master)).resize(size,size).png().toFile(`${native}/android/launcher-${size}.png`);
await writeFile(`${native}/android/foreground.xml`, '<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108"><group android:translateX="30" android:translateY="30" android:scaleX="2" android:scaleY="2"><path android:pathData="M18,16 L22,12 L18,8 M6,8 L2,12 L6,16 M14.5,4 L9.5,20" android:fillColor="#00000000" android:strokeColor="#0e1015" android:strokeWidth="2" android:strokeLineCap="round" android:strokeLineJoin="round"/></group></vector>');
await writeFile(`${native}/android/background.xml`, '<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle"><solid android:color="#0da2e7"/></shape>');
await writeFile(`${native}/android/adaptive.xml`, '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android"><background android:drawable="@drawable/codeforge_background"/><foreground android:drawable="@drawable/codeforge_foreground"/></adaptive-icon>');
for (const size of [40,60,80,120,152,167,180,1024]) await sharp(Buffer.from(mask)).resize(size,size).png().toFile(`${native}/ios/icon-${size}.png`);
for (const size of [44,50,150,310]) await sharp(Buffer.from(master)).resize(size,size).png().toFile(`${native}/windows/icon-${size}.png`);
await sharp(Buffer.from(mask)).resize(1024,1024).png().toFile(`${native}/huawei/icon-master.png`);
await copyFile('src/assets/brand/mark.svg',`${native}/splash/mark.svg`);
const { readdir } = await import('node:fs/promises');
const manifestPath = 'src/assets/brand/manifest.json';
const manifest = JSON.parse(await readFile(manifestPath,'utf8'));
for (const platform of ['android','ios','huawei','windows','splash']) for (const file of await readdir(`${native}/${platform}`)) manifest.assets.push({id:`${platform}-${file}`,name:`CodeForge ${platform} ${file}`,purpose:'Package integration candidate',sourceFile:'src/assets/brand/mark.svg',outputFile:`${native}/${platform}/${file}`,format:file.split('.').pop(),variant:file,platform,provenance:'New derivation of existing tile and Lucide mark',licenceStatus:'Lucide ISC; package/ownership review pending',productionApproved:false});
await writeFile(manifestPath,JSON.stringify(manifest,null,2)+'\n');
console.log('Generated CodeForge brand assets from the existing mark.');
